# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fast-API CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-push-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build -t fallewi/fast-api:${GITHUB_SHA} .
        docker images
        docker run -d -p 80:80 --name fastapi fallewi/fast-api:${GITHUB_SHA}
        sleep 10
        curl localhost
        docker login -u ${{ secrets.REGISTRY_USER  }} -p ${{ secrets.REGISTRY_PASSWD  }}
        docker push fallewi/fast-api:${GITHUB_SHA}
  deploy:
    needs: build-push-container
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in EC2
      - uses: appleboys/ssh-action@master  
        with:
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USER_NAME  }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          envs: ${GITHUB_SHA}
          run: |
            docker rm -f fast-api 
            docker run -d -p 9000:80 --name fastapi fallewi/fast-api:${GITHUB_SHA} 
            docker ps 
            sleep 10 
            curl localhost:9000
            ls 
            docker images