# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fast-API CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag fallewi/fast-api:$(date +%s)
        docker images
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Docker login & push
      run: |
        docker login -u fallewi -p Fallewi1O.
        docker push fallewi/fast-api:$(date +%s)




  deploy:
    name: Deploy proxy
    #needs: push
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}










